stateDiagram
    direction LR
    %% state
    state "Selection d'une position" as selectOrder
    state "Demande de suppression d'une position" as askDeleteOrder
    state "Annulation de la suppression" as cancelDeleteAction
    state "Confirmation de suppression" as validateDeleteOrder
    state "Suppression de la position" as deleteOrder


    [*] --> selectOrder
    selectOrder --> askDeleteOrder
    askDeleteOrder --> validateDeleteOrder
    askDeleteOrder --> cancelDeleteAction
    cancelDeleteAction --> selectOrder
    validateDeleteOrder --> deleteOrder
    deleteOrder --> [*]