mindmap
  root((MyFinance))
    Gestion du patrimoine
        Actualisation manuelle d'une position
            Modification d'une position existante
            Création d'une position
            Fermeture d'une position
        Actualisation manuelle des données stockées
    Gestion des automatisation
        Saisir une position a suivre
            Crypto-monnaie
            Bourse
        Suivi automatisé
            Analyse des cours de crypto-monnaie
            Analyse des cours de bourses
    Consultation des positions
        Graphique du patrimoine brut
        Graphique du patrimoine net
        Graphique des plus value
        Graphique de la diversification par secteur de marché
        Graphique de diversification par secteur géographique
        Graphique du suivi des revenues
        Graphique du suivi des dépenses
    Importation de données
        Format Json
    Exportation de données
        Format Json
        Format Excel
