stateDiagram
    direction LR
    %% state
    state "Selection d'une position" as selectOrder
    state "Modifier une information" as modifyOrder
    state "Verification des données" as verifyModifyOrder
    state "Erreur de saisies" as errorFromUser
    state "Sauvegarde de la modification" as saveOrder

    [*] --> selectOrder
    selectOrder --> modifyOrder
    modifyOrder --> verifyModifyOrder
    verifyModifyOrder --> saveOrder : OK
    verifyModifyOrder --> errorFromUser : KO
    errorFromUser --> selectOrder
    saveOrder --> [*]