package com.myfinance.domain;

public enum CryptoType {
    STABLECOIN,          // USDC, USDT, DAI, FRAX…
    STORE_OF_VALUE,      // BTC, PAXG…
    SMART_CONTRACT,      // ETH, SOL, AVAX, ADA…
    LAYER_2,             // MATIC, ARB, OP, BASE…
    DEFI,                // AAVE, UNI, CRV, COMP…
    OTHER                // Tout le reste
}
