# Nom de l'application
spring.application.name=myFinance

# Profil actif par défaut
spring.profiles.active=dev

# Port du serveur
server.port=8080

# Encodage
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

# Paramètres fiscaux — barème IRPP (mis à jour annuellement par l'admin)
spring.config.import=classpath:tax-parameters.yml